
import React from 'react';
import { ShieldAlert, AlertTriangle, Stethoscope, Brain, UserCheck, PhoneCall, ArrowLeft } from 'lucide-react';

interface Props {
  onBack: () => void;
}

const MedicalDisclaimer: React.FC<Props> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white font-sans">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-gray-500 hover:text-teal transition-colors mb-8 group"
        >
          <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </button>

        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center p-4 bg-amber-50 rounded-full text-amber-500 mb-6">
            <ShieldAlert size={48} />
          </div>
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-gray-900 mb-4">
            Terms & Medical <span className="text-teal">Disclaimer</span>
          </h1>
          <p className="text-gray-500 text-lg">Last Updated: March 2026</p>
        </div>

        <div className="space-y-12">
          {/* 1. Informational Purpose Only */}
          <section className="bg-slate-50 p-8 rounded-3xl border border-gray-100">
            <div className="flex items-start gap-4">
              <div className="bg-white p-3 rounded-2xl shadow-sm text-teal shrink-0">
                <Stethoscope size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-4 uppercase tracking-wide">1. Informational Purpose Only</h2>
                <p className="text-gray-600 leading-relaxed">
                  All content provided on the Medilens platform, including text, graphics, images, and information generated by our AI systems (Symptom Checker, Lab Report Analyzer, and Chatbots), is for <strong>informational and educational purposes only</strong>. 
                  It is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
                </p>
              </div>
            </div>
          </section>

          {/* 2. No Doctor-Patient Relationship */}
          <section className="p-8">
            <div className="flex items-start gap-4">
              <div className="bg-teal/10 p-3 rounded-2xl text-teal shrink-0">
                <UserCheck size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-4 uppercase tracking-wide">2. No Doctor-Patient Relationship</h2>
                <p className="text-gray-600 leading-relaxed">
                  Use of this platform <strong>does not establish a doctor-patient relationship</strong> between the user and Medilens. 
                  The platform is a digital tool designed to assist in health literacy, not a clinical service provider.
                </p>
              </div>
            </div>
          </section>

          {/* 3. AI Limitations */}
          <section className="bg-slate-50 p-8 rounded-3xl border border-gray-100">
            <div className="flex items-start gap-4">
              <div className="bg-white p-3 rounded-2xl shadow-sm text-blue-500 shrink-0">
                <Brain size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-4 uppercase tracking-wide">3. AI Limitations</h2>
                <p className="text-gray-600 leading-relaxed">
                  Our AI models are trained on large datasets to provide general health guidance. However, AI can make mistakes, overlook critical nuances, or provide outdated information. 
                  The outputs should be treated as preliminary guides and must be verified by a human medical professional.
                </p>
              </div>
            </div>
          </section>

          {/* 4. Not Responsible for Medical Decisions */}
          <section className="p-8">
            <div className="flex items-start gap-4">
              <div className="bg-red-50 p-3 rounded-2xl text-red-500 shrink-0">
                <AlertTriangle size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-4 uppercase tracking-wide">4. Not Responsible for Medical Decisions</h2>
                <p className="text-gray-600 leading-relaxed">
                  Medilens and its developers are <strong>not responsible or liable</strong> for any advice, course of treatment, diagnosis, or any other information, services, or products that you obtain through this platform. 
                  You are solely responsible for any decisions you make based on the information provided here.
                </p>
              </div>
            </div>
          </section>

          {/* 5. User Responsibility */}
          <section className="bg-slate-50 p-8 rounded-3xl border border-gray-100">
            <div className="flex items-start gap-4">
              <div className="bg-white p-3 rounded-2xl shadow-sm text-gray-700 shrink-0">
                <UserCheck size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-4 uppercase tracking-wide">5. User Responsibility</h2>
                <p className="text-gray-600 leading-relaxed">
                  Users are encouraged to confirm any information obtained from or through this platform with other sources and review all information regarding any medical condition or treatment with their physician or other professional healthcare provider. 
                  <strong>Never disregard professional medical advice or delay seeking it because of something you have read on this platform.</strong>
                </p>
              </div>
            </div>
          </section>

          {/* 6. Emergency Instructions */}
          <section className="bg-red-600 p-8 rounded-3xl text-white shadow-xl shadow-red-200">
            <div className="flex items-start gap-4">
              <div className="bg-white/20 p-3 rounded-2xl text-white shrink-0">
                <PhoneCall size={24} />
              </div>
              <div>
                <h2 className="text-xl font-bold mb-4 uppercase tracking-wide">6. Emergency Instructions</h2>
                <p className="leading-relaxed mb-4">
                  If you think you may have a medical emergency, call your doctor, go to the nearest hospital emergency department, or call emergency services immediately.
                </p>
                <div className="inline-block bg-white text-red-600 px-6 py-2 rounded-full font-bold text-sm">
                  DO NOT USE THIS APP FOR EMERGENCIES
                </div>
              </div>
            </div>
          </section>
        </div>

        <div className="mt-20 pt-10 border-t border-gray-100 text-center">
          <p className="text-gray-400 text-sm">
            By using Medilens, you acknowledge that you have read, understood, and agreed to these terms.
          </p>
          <button 
            onClick={onBack}
            className="mt-8 bg-teal text-white px-10 py-4 rounded-full font-bold hover:bg-teal-dark transition-all shadow-lg"
          >
            I Understand, Return Home
          </button>
        </div>
      </div>
    </div>
  );
};

export default MedicalDisclaimer;
